config/routes.rb
SampleApp::Application.routes.draw do

  resources :tags, only: [] do
    member do
      get :tag_followers
    end
  end

  resources :tag_relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'tags/:tag' => 'microposts#tags', as: :tag
  get '/microposts' => 'microposts#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :microposts, through: :taggings

	has_many :tag_relationships, foreign_key: "followed_tag_id", dependent: :destroy
	has_many :followed_tags, through: :tag_relationships, source: :followed_tag
    has_many :reverse_relationships, foreign_key: "followed_tag_id", class_name: "TagRelationship", dependent: :destroy
    has_many :tag_followers, through: :reverse_relationships, source: :tag_follower


    def self.tagged_with(name)
      Tag.find_by_name!(name).microposts
    end

	def self.tag_counts
	  Tag.select("tags.*, count(taggings.tag_id) as count").
	    joins(:taggings).group("taggings.tag_id")
	end

	def tag_list
	  tags.map(&:name).join(", ")
	end

	def tag_list=(names)
	  self.tags = names.split(",").map do |n|
	    Tag.where(name: n.strip).first_or_create!
	  end
	end

	private

    def tag_params
      params.require(:tag).permit(:name, :id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @feed_items = Micropost.tagged_with(params[:tag]).paginate(page: params[:page])
  end

  def index
  end
  
end

app/views/tags/_follow_tag_form.html.erb
<div id="follow_tag_form">
	<% if current_user.following_tag?(@tag) %>
		<%= render 'users/unfollow_tag' %>
	<% else %>
		<%= render 'users/follow_tag' %>
	<% end %>
</div>

app/views/tags/index.html.erb
<div id="tag_cloud">
  <% tag_cloud Micropost.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

app/views/tags/show.html.erb
<section>
	<% if signed_in? %>
		<%= render 'follow_tag_form' %>
	<% else %>
		<h3>Want to share something? <%= link_to "Sign Up", signup_path %> or <%= link_to "Log In", signin_path %><h3>
	<% end %>
</section>
<h1><%= Tag.name %></h1>
<%= render 'shared/feed' %>